apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-node-server
  template:
    metadata:
      labels:
        app: simple-node-server
    spec:
      containers:
      - name: simple-node-server
        image: devpaing/simple-server:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Never
      priorityClassName: system-node-critical
